### ISSUE TITLE
Slides locked for editing, no way out

### ISSUE THREAD

**Issue by felix-wo** [eerotal/LibreSignage#29] opened 2018-12-04 14:48 UTC
If I was logged in on a second browser tab I get "You can't edit this slide because someone else is already editing it." The slide keeps being locked even after "Settings" > "Logout other sessions".

**Comment by felix-wo** [comment] 2018-12-04 19:50
> That happens because there's a time based cutoff in the slide locks, ie. if a user leaves the editor his locked slides will automatically be released after a certain time.

Maybe that certain time is longer than necessary?

> Now that I think about it I should definitely unlock all slides on logout too.

Definitely, that should happen.

I’ll observe further, if and when the problem occurs …

**Comment by felix-wo** [comment] 2018-12-04 20:15
Update: I’ve just lost connection accidently (no WLAN connection) and then it happens. No chance to unlock the respective slide, blocked for work for a rather long time.

**Comment by felix-wo** [comment] 2018-12-04 20:50
When I loose server connection like this, I afterwards get other authorization errors, too. After logoff I can’t even login any more, no matter what user account.

**Comment by felix-wo** [comment] 2018-12-05 13:02
Fine! I’m willing to do further testing.

**Comment by felix-wo** [comment] 2018-12-05 13:44
Just got kicked out of the system after just having edited a slide, having saved it and trying to preview. It gave a dialog, this action wasn’t authorized. Had to re-login. I experience more such problems with login and access regularly, though can’t reproduce them yet. I’ll report if I know better … I get the impression, there should some systematic testing and debugging work be done on this field …

**Comment by eerotal** [comment] 2018-12-05 14:00
I made some changes to the slide lock releasing code so that slides are released on logout and when the editor is closed. I also reduced the lock cutoff time to 5 minutes. There's still one case where the system sometimes has to fall back to the cutoff based lock releasing: If a user closes the tab where they are editing a slide, the editor doesn't always have enough time to release the locked slide. That can't really be fixed though, since it's a limitation of the browser. The slide will get released after the 5 minute cutoff though.

The access problems are odd since I've never seen anything like that. What browser do you use? Do you use incognito mode? Does your browser block cookies? Any other details you'd like to give?

**Comment by felix-wo** [comment] 2018-12-06 00:55
These improvements sound promising. Lately, I’ve often been using a "private" window on firefox for LibreSignage to prevent it loading old code when you pushed new things to the development branch. I’ll see, I’ll observe things further and try to be able to reproduce errors if they occur.

What I can tell so far: User sessions seem to expire due to inactivity after a certain time. From the Editor it doesn’t just logoff and show the login page again, though. Instead it shows the blue "not authorized" box, especially if you click other slides on the editor page. I’m not sure yet what it does if there’s yet unsaved changes in the editor and the session expires – do they get lost?

Just now I got an incidence where an uploaded image and its thumbnail got broken, and I don’t know how this happened. I could re-upload the image and it worked again, just as before.

**Comment by felix-wo** [comment] 2018-12-06 10:53
The browser window was left open when that happened to me.

**Comment by eerotal** [comment] 2019-03-01 06:41
The API interface and session management code have undergone big changes in *next* since this issue was opened and I haven't been able to reproduce the bug, so I'm closing this for now. If the issue still exists a new issue can be opened later.

**Closed by eerotal** 2019-03-01 06:41 UTC
Labels: bug
