### ISSUE TITLE
Video makes Chrome run out of memory

### ISSUE THREAD

**Issue by evilaprojects** [eerotal/LibreSignage#101] opened 2019-12-16 00:40 UTC
I uploaded only 1 video (40s duration )to a queue and accessed from Chrome. After some minutes Chrome crashes because there is no memory left. 
How can I avoid that? I thought there was some caching system in place but it keeps crashing after a while.

**Comment by evilaprojects** [comment] 2019-12-16 11:19
To mention the video is hosted in DigitalOcean Space

**Comment by eerotal** [comment] 2019-12-16 19:51
Interesting, it seems like there's a memory leak in the display JavaScript then. I might know where the problem is already but I'll have a closer look at the code soon.

**Comment by evilaprojects** [comment] 2019-12-16 20:25
Is there something I can do to help you or something I can try in order to fix it and be able to use it?

**Comment by eerotal** [comment] 2019-12-17 18:59
I'll try to write a fix for the bug soon so if you could test it once it's finished that would be great. Other than that I don't think there's much you can do unless you want to try writing a patch yourself. You can't really work around the issue either as the problem is in the display rendering code.

**Comment by evilaprojects** [comment] 2019-12-18 07:10
Ok I'll test it as soon as it is ready and I'll give you feedback. Thank
you

**Comment by evilaprojects** [comment] 2019-12-18 09:18
Ok thank you I'll give you feedback then

**Comment by eerotal** [comment] 2019-12-19 17:09
Could you check the following things so I have a bit more information:

- Version of LibreSignage.
- Version of Chrome.
- What operating system are you running?
- How much memory does your system have?
- What is the file format of the video that crashes the browser?
- Is the slide with the video in it the only slide in the queue?

**Comment by evilaprojects** [comment] 2019-12-20 10:28
Hi,

v1.1.0-beta-2
v78 chromium
buster
1gb
.mov
yes but also tried with more slides and same happens

Thank you

**Comment by eerotal** [comment] 2020-01-02 12:13
This turned out to be a rather tricky issue, but I wrote a patch that might improve the situation a bit. I think the problems you are seeing are actually due to a bug in Chrome (https://bugs.chromium.org/p/chromium/issues/detail?id=969049), which causes a memory leak when removing HTML5 video tags from the DOM. That bug is apparently already fixed, although I'm not sure if it's included in the latest release of Chrome yet.

I tested this issue on Firefox too but couldn't reproduce the memory leak there. Could you give Firefox a try to see whether the issue is in fact due to bug in Chrome?

Please build LibreSignage from the updated *v1.x.x* branch that includes the new patch.

**Comment by evilaprojects** [comment] 2020-01-05 01:28
How can I get the image from v1.x.x using Docker? I've tried with eerotal/libresignage:v1.x.x but it doesn't work
Thanks

**Comment by eerotal** [comment] 2020-01-05 09:41
Ah, there are currently no nightly builds from the v1.x.x branch so the Docker images don't contain the latest patch yet. I'll enable nightly builds so you can test using Docker.

**Comment by eerotal** [comment] 2020-01-05 10:02
Okay, you should now get the latest patch by pulling `eerotal/libresignage:v1.x.x-nightly`.

**Comment by evilaprojects** [comment] 2020-03-07 17:46
Hello, 

just to confirm, now the correct version to get the patch is eerotal/libresignage:v1.1.x-nightly, isn't it? Is it also incorporated into latest tag?

I was unable to test the former patch.

Thank you

**Comment by evilaprojects** [comment] 2020-03-07 20:09
I've tested eerotal/libresignage:v1.1.x-nightly and still crashes on Chrome

**Comment by eerotal** [comment] 2020-03-07 21:39
That's great! If you have any further issues be sure to report them. I'll close this one.

**Closed by eerotal** 2020-03-07 21:39 UTC
Labels: bug
