### ISSUE TITLE
Video stops being displayed after a certain amount of time

### ISSUE THREAD

**Issue by ynl1** [eerotal/LibreSignage#52] opened 2019-03-25 15:48 UTC
Ok, I felt this needed a new issue. Basically, I have a slide that's just a fullscreen video, and another slide with some text on it.

The video displays fine, all is good. But after some time, the video isn't displayed anymore, it's just the blank background color of LibreSignage's slide system. 

I know it's a problem with LibreSignage because i have tried on 3 other computers and once one goes down, they all do.

I'm using beta version 1.0.0, any help is appreciated.

**Comment by eerotal** [comment] 2019-03-25 19:25
This is interesting. Do slides change after the video stops playing? Does the text-only slide still work? Any error messages in the browser developer console?

**Comment by ynl1** [comment] 2019-03-25 20:10
The slides do change like they should, the text-only slide still works. I haven't looked at the developer console yet, will report back when i do

**Comment by ynl1** [comment] 2019-03-26 02:36
Ok, Just checked the console, this is what it outputs (when the error occurs):

4
main.js:19684 DisplayController: Queue update.
main.js:19687 DisplayController: Failed to update queue.
main.js:20693 APISession: Renewal failed.
main.js:19687 DisplayController: Failed to update queue.
main.js:20454 Uncaught (in promise) APIError: 
API Error (3): Not authenticated.
	at /var/www/localhost/api/modules/module_auth.php @ ln: 29
Server stack trace:
	#0 /var/www/localhost/api/api.php(102): APIAuthModule->run(Object(APIEndpoint))
	#1 /var/www/localhost/api/endpoint/auth/auth_session_renew.php(20): APIEndpoint->__construct(Array)
#2 {main}


	at /var/www/localhost/api/modules/module_auth.php @ ln: 29
Server stack trace:
	#0 /var/www/localhost/api/api.php(102): APIAuthModule->run(Object(APIEndpoint))
	#1 /var/www/localhost/api/endpoint/auth/auth_session_renew.php(20): APIEndpoint->__construct(Array)
#2 {main}


    at XMLHttpRequest.<anonymous> (http://192.168.4.211/app/js/main.js:20085:15)
2
main.js:19687 DisplayController: Failed to update queue.
main.js:19684 DisplayController: Queue update.
main.js:19687 DisplayController: Failed to update queue.
main.js:19684 DisplayController: Queue update.

**Comment by eerotal** [comment] 2019-03-26 12:45
About how long does it take for the display to stop working?

**Comment by ynl1** [comment] 2019-03-26 15:46
I'm sorry, I should have worded the title differently, it just happens randomly, sometimes in 10 minutes, other times in 2 hours.

**Comment by eerotal** [comment] 2019-03-26 18:46
This is quite a time-consuming issue to debug because it seems to be rather intermittent. I really need to reproduce and fix this though because it's a serious issue affecting the usability of the system.

**Comment by infomaniac50** [comment] 2019-03-30 04:23
### Observations
I've seen hints of this too. I didn't do anything with it though since I was busy testing other things. I just refreshed the page and logged in again.

### Question & Possible Issue
Does this application handle more than one request at a time? If the only PHP process available is being held open by a video stream then other requests might fail.

This really depends on Apache and what MPM your using. It's why I suggested that you serve media files statically in #53. Access control is a requirement though so I'm not sure how you can resolve this one.

### Solutions?

- Chunking your responses with "206 Partial Content" might help.
- Make sure your code is as lock free as possible. Opening files for long periods with exclusive access will stall other PHP processes.
- If you don't need write access to a file then don't request it. Opening a file as read-only tells the OS that you won't change stuff in the middle of another processes IO request.

**Comment by eerotal** [comment] 2019-04-03 16:35
> Does this application handle more than one request at a time? If the only available PHP process is being held open by a video stream then other requests might fail.

Now that I think about it, the issue might actually be due to something like this but on the client side instead of the server side. That is, if the client is loading a video, the session renewal process might fail because an API call is blocking. I'll debug this soon when I have more time, I'm kinda busy right now.

**Comment by infomaniac50** [comment] 2019-04-04 19:54
After reading up on file locking I have learned that Unix-like systems and Windows systems have different default locking schemes.

I got curious after Windows wouldn't let me move files when I had them open for reading. Windows applications must explicitly opt-out of file locking. All file access is exclusive to the application that opened it, by default. 

Unix-like systems are the opposite. On Unix-like systems such as Linux and BSD (macOS), applications must explicitly opt-in to file locking. All file access is shared by default.

This comment probably isn't relevant, but I thought it was interesting. Maybe it's something to keep in mind if you ever make a Windows build. I don't know if PHP "translates" this for Windows.

**Comment by eerotal** [comment] 2019-04-05 18:05
I haven't read about file locking on Windows but yes, that's how it works on Unix/Linux systems; files aren't automatically locked. LibreSignage uses advisory PHP file locks via the `flock()` and `fclose()` calls, which is a system for informing PHP scripts that a file is locked. That also means other processes won't respect the locks, which in this case isn't really a problem.

The documentation page for `flock()` does mention that the function also works on Windows but it uses mandatory file locks instead of advisory locks, which shouldn't cause any problems. That said, I'm not planning to make a Windows build in the near future so it's really a non-issue anyway.

**Comment by eerotal** [comment] 2019-04-06 18:02
I managed to track down one bug that certainly causes the issues @ynl1 mentioned. There's one catch though; it only manifests itself when the display page and some other page of the web interface are open in different tabs of the same browser simultaneously. Did you have any other web interface pages open when you saw the issue?

**Comment by infomaniac50** [comment] 2019-04-06 21:13
I don't remember if I had multiple tabs open. For my case, it would certainly be a plausible explanation.

I'm a tab-meister for sure. Sometimes I have 50+ tabs open if I'm working on multiple projects.

**Comment by eerotal** [comment] 2019-04-07 12:47
Fixing the bug I found might fix the original issue then. I'll finish the bugfix and push it to the `next` branch so you can it a try.

By the way, in case you're using the LibreSignage Docker images, the eerotal/LibreSignage repo now contains automatic nightly builds. The images are rebuilt every night from the latest sources in `next`. You can use them by pulling `eerotal/LibreSignage:nightly` via Docker.

**Comment by eerotal** [comment] 2019-04-07 18:24
I tried one fix in c81195ba2d962c29c50c42019cdd7cc1520ccf54 but noticed it doesn't actually work yet. I'll try something else.

**Comment by infomaniac50** [comment] 2019-04-08 22:10
> You can use them by pulling `eerotal/LibreSignage:nightly` via Docker.

FYI/Reminder for myself. Docker repository names must be all lowercase. I tripped up twice because I copy and paste too much.

Use this instead.
```
docker pull eerotal/libresignage:nightly
```

**Comment by infomaniac50** [comment] 2019-04-08 23:56
What is the maximum POST time for media uploads? I got a CONNECTION_RESET error when trying to upload through a 6Mb/s VPN. The file is 159MB so that would take approximately 212 seconds.

Is there a maximum execution time for media downloads, aka. slide display? @ynl1 hasn't confirmed or denied whether they had multiple tabs open. I'm wondering if they uploaded a really long video. Then when they go to display the video it gets cut off by PHP's maximum execution time.

**Comment by ynl1** [comment] 2019-04-09 00:12
Hello, Sorry for the late reply, I didn't have multiple tabs open / many instances on different tabs. Also a slight correction, they don't all fail at the same time. Instead, they fail at different times.

**Comment by eerotal** [comment] 2019-04-09 04:34
> Is there a maximum execution time for media downloads, aka. slide display?

There probably is but I'm not sure how long it is. I'll check that. I think it'd be a good idea to implement some sort of chunked/resumable file uploads to fix any problems with this.

> Then when they go to display the video it gets cut off by PHP's maximum execution time.

This seems like a possible explanation. While fixing the bug I found earlier, I did occasionally see some weird behaviour with video downloads aswell.

> Hello, Sorry for the late reply, I didn't have multiple tabs open / many instances on different tabs. Also a slight correction, they don't all fail at the same time. Instead, they fail at different times.

And this confirms I have more bug fixing to do ;)

**Comment by infomaniac50** [comment] 2019-04-11 21:35
I'm getting this intermittently. I'm not sure what is causing it though. I have three clients going at the same time and it always seems to happen when I'm not looking.

There is one thing that will kill it for sure and that is a javascript error. If an unhandled error occurs then the client will stop processing that block of code. Asynchronous code may still run but any that is in the same context as the error won't run anymore.

**Comment by eerotal** [comment] 2019-04-24 06:13
Okay, I'm working on yet another attempted fix for this issue, which I hope will solve it once and for all. I still *think* the issue is due to multiple tabs renewing sessions at the same time, which then causes problems with outdated session tokens. The solution I came up with is to run the API interface code in a SharedWorker, to which the individual tabs/windows connect to in order to call API endpoints. This should fix the issue because now only one APIInterface instance is handling session renewal centrally for all tabs. The fix requires quite a few changes though, so it might take some time to get it ready but I have most of it figured out by now. I _really_ hope this one works!

**Comment by eerotal** [comment] 2019-04-24 06:49
There is one issue with my solution though: SharedWorkers are completely broken in Firefox starting from version 57. SharedWorkers should be **shared** between tabs but because of a bug in Firefox they aren't and that basically undermines the fix. Session renewal does still work like it used to before the fix, but the original bug persists. Right now I haven't managed to come up with other ways to fix the issue though, so I'll probably have to conclude LibreSignage is (slightly) incompatible with Firefox 57+ until they fix the SharedWorker bug.

**Comment by eerotal** [comment] 2019-04-26 16:21
I merged a fix into *next* for you to test. The fix basically makes session tokens permanent per-session, ie. new tokens aren't generated every time a session is renewed; only the session expiration time is updated. This **should** at least fix the problems I saw when multiple tabs renewed sessions simultaneously. 

I'm not yet sure whether this fixes the problems with only a single tab open @ynl1 reported. I think it's worth trying out though.

**Comment by ynl1** [comment] 2019-04-26 18:51
Ok. I will try it out!

**Comment by eerotal** [comment] 2019-05-09 05:55
I'm closing this one for now because this is the only issue keeping me from releasing v1.0.0 and I haven't managed to make the display fail in my tests. Also, if you haven't tested the fix yet, please test it using the new v1.0.x-dev branch since next has already moved forward onto v1.1.x development.

If the bug still persists later you can reopen this issue and I'll look into it. In that case any fixes will be in future patch releases for v1.0.x.

**Closed by eerotal** 2019-05-09 05:55 UTC
Labels: bug

**Comment by bandicootdancing** [comment] 2019-12-10 19:17
I've also been experiencing a similar issue. All of my uploaded media through LibreSignage breaks after one week but sometimes it's days or two weeks. In this case all of the slides still transition and contain text as they should but each photo is broken and only displays a small x instead of the media. Once I refresh the page I'm prompted to sign in again.

Maybe this is a new issue but can a public slideshow option for queues be implemented where there is no sign in needed to view?

**Comment by eerotal** [comment] 2019-12-11 08:20
@bandicootdancing What version of LibreSignage are you on? A bug related to this was fixed in v1.0.2 just recently. The public queue thing is also on my TODO list but I haven't had the time to work on it yet.

**Comment by bandicootdancing** [comment] 2019-12-11 19:36
Still on v1.0.0 from earlier this year. I tried upgrading but still shows 1.0.0.

**Comment by eerotal** [comment] 2019-12-11 20:04
How did you try to upgrade? The version number at the bottom of the web interface should change if the new version is actually installed.

**Comment by evilaprojects** [comment] 2019-12-16 11:13
I'm running LibreSignage v1.1.0-beta-2 from Docker image and my problem is that once a browser is running a queue with big video on a loop, it makes the browser run out of memory. If you monitor the memory it keeps going up until the browser crashes.

**Comment by eerotal** [comment] 2019-12-16 19:53
@evilaprojects I believe this issue is slightly different to the one you are seeing and this one *should* already be fixed.

**Comment by bandicootdancing** [comment] 2019-12-16 22:57
I just need to learn how to use git correctly. Updated master branch to v1.0.1-10-g8a090c2 but switching to v1.x.x doesn't update anything.

**Comment by eerotal** [comment] 2019-12-17 19:50
There seems to be a problem in the v1.0.2 tag in the master branch. I have apparently tagged it in v1.x.x and because of how `git describe` works the release tag is not properly reported in master. I'll sort that out for v1.0.3.  The correct version, v1.0.2, should be reported if you build from v1.x.x though.

Did you run `git pull` before building to make sure the local repo is up-to-date? You should also probably checkout the v1.0.2 tag by running `git checkout v1.0.2` to only build the changes included in the release especially if you run LibreSignage on a production system.

**Comment by bandicootdancing** [comment] 2019-12-19 16:08
Thanks for the info. I was able to update to the latest master but then I was having the issue after a single queue rotation. I finally had to git clone the project to a new directory and start over from there. Not sure what I was doing wrong but was able to check out v1.0.2. It's only been a day but still up.

**Comment by eerotal** [comment] 2019-12-19 17:03
Great! If you see the issue again be sure to tell me so I can look into it.
