### ISSUE TITLE
Can't import video

### ISSUE THREAD

**Issue by ynl1** [eerotal/LibreSignage#68] opened 2019-05-17 00:25 UTC
So i have tried the patch to issue #52 and now it's worse. The editor freezes up and i have to reload the page, but in doing so it says im no longer the owner of the queue. When i try to import the video is says the syntax is wrong, despite me copying it from the documentation. I'm using Chrome on a machine with KDE Neon.

**Comment by eerotal** [comment] 2019-05-18 17:21
This might have something to do with the recent patch for #66. Which branch did you build from?

**Comment by ynl1** [comment] 2019-05-18 19:31
No, this was before you released 1.1.0, I was about to tell you the results
but you closed the issue, so I made this one. I haven't tried the new
release though.

**Comment by eerotal** [comment] 2019-05-18 19:40
v1.1.0 isn't actually released yet. The v1.x.x and next branches contain the changes for that release though. You can check whether you're on v1.0.0 or some other version by looking at the version number in the web interface footer. If it only says v1.0.0 then you're on v1.0.0 but if it says something like v1.0.0-<commit hash> then you're on a more recent dev version.

**Comment by ynl1** [comment] 2019-05-23 22:57
I am having the same problems with the latest version.

**Comment by eerotal** [comment] 2019-05-24 03:37
Ok, I need to take a closer look at this.

**Comment by eerotal** [comment] 2019-05-25 08:03
I can't seem to reproduce this problem on either the stable version 1.0.0 or in the development branches for v1.0.1 or v1.1.0. What were the exact steps you took when this issue occured? Could you paste the markup that caused problems here? Also, please copy the LibreSignage version number from the web interface footer and paste the whole thing here.

**Comment by eerotal** [comment] 2019-08-19 15:14
As I'm not able to reproduce the issue and there's no further input from @ynl1, I will now close the issue.

**Closed by eerotal** 2019-08-19 15:14 UTC
Labels: bug
